import React from "react";

const TermsAndConditions = () => {
  // Exact data mapping to preserve every character and bullet point
  const legalSections = [
    { type: "header", content: "Terms and Conditions" },
    { type: "text", content: "These Terms and Conditions govern your access to and use of the WorkforceFlow AI platform, website, software, applications and related services." },
    { type: "text", content: "By creating an account, using the platform, accessing a free trial, or subscribing to our services, you agree to be bound by these Terms." },
    {
      title: "1. About us",
      content: [
        "WorkforceFlow AI Ltd is a company incorporated in England and Wales with company number 17038602.",
        "In these Terms, “WorkforceFlow AI”, “we”, “us” or “our” means WorkforceFlow AI Ltd."
      ]
    },
    {
      title: "2. Definitions",
      content: [
        "In these Terms:",
        "Account means the account created by or for a User to access the Services.",
        "Customer Data means all information, documents, files, content, records, customer details, supplier details, employee details, job information, quotations, invoices and other data uploaded, entered or generated by you through the Services.",
        "Documentation means any user guidance, help content, technical notes, support materials or product information we provide.",
        "Fees means the charges payable for use of the Services.",
        "Services means the WorkforceFlow AI website, platform, software, applications, tools, functionality, APIs and related services.",
        "User, you or your means the business, organisation, sole trader or authorised individual using the Services."
      ]
    },
    {
      title: "3. Business use only",
      content: [
        "The Services are intended for business use only and are not intended for personal, domestic or consumer use.",
        "By using the Services, you confirm that you are acting for business purposes and that you have authority to bind the business or organisation you represent."
      ]
    },
    {
      title: "4. Licence to use the Services",
      content: [
        "Subject to these Terms and payment of any applicable Fees, we grant you a limited, revocable, non-exclusive, non-transferable right to access and use the Services for your internal business purposes.",
        "You must not:",
      ],
      bullets: [
        "copy, modify, reverse engineer or attempt to extract source code from the Services;",
        "resell, sublicense or make the Services available to third parties without our written consent;",
        "use the Services unlawfully or in a way that damages our systems, reputation or other users;",
        "attempt to bypass security, usage limits or access controls;",
        "use the Services to store or transmit malicious code."
      ]
    },
    {
      title: "5. Free trials and subscriptions",
      content: [
        "We may offer a free trial or introductory access period.",
        "At the end of any free trial, continued access may require payment of Fees. We may change or withdraw free trials at any time.",
        "Subscription Fees, billing frequency and package details will be set out on our website, order form, invoice or subscription page."
      ]
    },
    {
      title: "6. User responsibilities",
      content: [
        "You are responsible for:",
      ],
      bullets: [
        "ensuring all information entered into the Services is accurate and lawful;",
        "maintaining the confidentiality of usernames, passwords and access credentials;",
        "ensuring your users comply with these Terms;",
        "obtaining any consents required from your customers, suppliers, employees or contractors;",
        "checking quotations, invoices, tax calculations, CIS/VAT treatment and other outputs before relying on them."
      ],
      footer: "The Services are designed to support business administration, but they do not replace professional judgement, accounting advice, tax advice or legal advice."
    },
    {
      title: "7. Customer Data",
      content: [
        "You retain ownership of your Customer Data.",
        "You grant us a limited licence to host, process, transmit, back up and use Customer Data as necessary to provide, maintain, secure and improve the Services.",
        "We may use aggregated and anonymised data for analytics, product improvement, benchmarking and commercial insight, provided that such data does not identify you, your customers or any individual."
      ]
    },
    {
      title: "8. Data protection and privacy",
      content: [
        "Each party shall comply with applicable data protection laws, including the UK GDPR and the Data Protection Act 2018.",
        "Where we process personal data on your behalf as part of the Services, you will usually act as the data controller and we will act as your data processor.",
        "You are responsible for ensuring that you have a lawful basis to collect and upload personal data into the Services.",
        "Our handling of personal data is described in our Privacy Policy and, where applicable, any Data Processing Agreement we put in place with you."
      ]
    },
    {
      title: "9. Sensitive personal data",
      content: [
        "You must not upload special category personal data unless it is necessary, lawful and supported by appropriate safeguards.",
        "This includes data relating to:",
      ],
      bullets: [
        "health;",
        "racial or ethnic origin;",
        "political opinions;",
        "religious or philosophical beliefs;",
        "trade union membership;",
        "sexual orientation;",
        "biometric or genetic data."
      ]
    },
    {
      title: "10. Cookies",
      content: [
        "We use cookies and similar technologies to operate and improve the Services.",
        "Further details are set out in our Privacy Policy and Cookie Policy.",
        "Non-essential cookies will only be used where legally permitted and, where required, with your consent."
      ]
    },
    {
      title: "11. Intellectual property",
      content: [
        "All intellectual property rights in the Services, software, platform, designs, workflows, templates, AI features, branding, documentation and related materials belong to WorkforceFlow AI Ltd or our licensors.",
        "Nothing in these Terms transfers ownership of our intellectual property to you.",
        "You must not use our name, logo, branding or product materials without our prior written consent."
      ]
    },
    {
      title: "12. AI-assisted functionality",
      content: [
        "The Services may include AI-assisted features, including support for quote drafting, workflow suggestions, line item recommendations, pricing assistance or automation.",
        "AI-generated outputs may be incomplete, inaccurate or unsuitable for your specific circumstances.",
        "You are responsible for reviewing and approving all AI-assisted outputs before using them with customers, suppliers, employees or third parties."
      ]
    },
    {
      title: "13. Third-party services",
      content: [
        "The Services may integrate with or rely on third-party providers, including hosting providers, payment processors, analytics tools, authentication providers and communication platforms.",
        "We are not responsible for failures, outages or acts of third-party providers outside our reasonable control."
      ]
    },
    {
      title: "14. Availability and maintenance",
      content: [
        "We will use reasonable commercial efforts to keep the Services available.",
        "However, we do not guarantee that the Services will be uninterrupted, error-free, secure from all threats, or available at all times.",
        "Access may be affected by maintenance, updates, security incidents, third-party outages, internet disruption or events beyond our control."
      ]
    },
    {
      title: "15. Support",
      content: [
        "We may provide support through email, in-app messaging, online help resources or other channels we make available.",
        "Support availability may depend on your subscription plan."
      ]
    },
    {
      title: "16. Fees and payment",
      content: [
        "You must pay all Fees in accordance with the applicable subscription plan, invoice or payment terms.",
        "Unless otherwise stated:",
      ],
      bullets: [
        "Fees are payable in advance;",
        "Fees are exclusive of VAT or other applicable taxes;",
        "late payment may result in suspension or termination of access."
      ],
      footer: "We may change Fees by giving reasonable notice."
    },
    {
      title: "17. Suspension",
      content: [
        "We may suspend access to the Services where:",
      ],
      bullets: [
        "Fees are overdue;",
        "we reasonably suspect misuse or unlawful activity;",
        "continued access may create a security, legal or operational risk;",
        "you materially breach these Terms."
      ]
    },
    {
      title: "18. Termination",
      content: [
        "Either party may terminate the subscription in accordance with the applicable plan, order form or cancellation process.",
        "We may terminate or suspend access immediately if you materially breach these Terms.",
        "On termination:",
      ],
      bullets: [
        "your right to use the Services ends;",
        "you remain liable for any unpaid Fees;",
        "we may delete or restrict access to Customer Data after a reasonable retention period, unless legally required to retain it."
      ]
    },
    {
      title: "19. Export of data",
      content: [
        "Where reasonably practicable, we may provide tools to allow you to export Customer Data before termination.",
        "You are responsible for exporting any data you wish to retain before your account is closed."
      ]
    },
    {
      title: "20. Warranties and disclaimers",
      content: [
        "We will use reasonable skill and care in providing the Services.",
        "However, the Services are provided on an “as is” and “as available” basis.",
        "We do not warrant that:",
      ],
      bullets: [
        "the Services will meet all of your requirements;",
        "the Services will be uninterrupted or error-free;",
        "all outputs will be accurate, complete or suitable;",
        "the Services will be compatible with all systems or devices."
      ]
    },
    {
      title: "21. Limitation of liability",
      content: [
        "Nothing in these Terms limits or excludes liability for:",
      ],
      bullets: [
        "death or personal injury caused by negligence;",
        "fraud or fraudulent misrepresentation;",
        "any liability that cannot legally be excluded."
      ],
      footer: "Subject to the above, we shall not be liable for: loss of profits; loss of revenue; loss of business; loss of goodwill; loss of anticipated savings; indirect or consequential loss; loss arising from inaccurate data entered by you; reliance on unreviewed AI-generated outputs. Our total liability arising out of or in connection with the Services shall be limited to the total Fees paid by you to us in the 12 months preceding the event giving rise to the claim."
    },
    {
      title: "22. Indemnity",
      content: [
        "You agree to indemnify us against losses, claims, damages, costs and expenses arising from:",
      ],
      bullets: [
        "your unlawful use of the Services;",
        "Customer Data uploaded by you;",
        "breach of these Terms;",
        "infringement of third-party rights;",
        "failure to obtain required permissions or consents."
      ]
    },
    {
      title: "23. Changes to the Services or Terms",
      content: [
        "We may update the Services, Documentation, Fees or these Terms from time to time.",
        "Where changes are material, we will provide reasonable notice.",
        "Continued use of the Services after changes take effect will constitute acceptance of the updated Terms."
      ]
    },
    {
      title: "24. Notices",
      content: [
        "We may send notices to you by email, in-app notification or to the contact details associated with your Account.",
        "You may contact us using the contact details published on our website."
      ]
    },
    {
      title: "25. Assignment",
      content: [
        "You may not assign or transfer your rights under these Terms without our prior written consent.",
        "We may assign or transfer our rights and obligations under these Terms as part of a merger, restructuring, sale of assets, group reorganisation or business transfer."
      ]
    },
    {
      title: "26. No waiver",
      content: [
        "A delay or failure to enforce any right under these Terms does not constitute a waiver of that right."
      ]
    },
    {
      title: "27. Severability",
      content: [
        "If any part of these Terms is found to be invalid, unlawful or unenforceable, the remaining provisions shall continue in full force and effect."
      ]
    },
    {
      title: "28. Third-party rights",
      content: [
        "Except where expressly stated, no third party has rights to enforce these Terms under the Contracts (Rights of Third Parties) Act 1999."
      ]
    },
    {
      title: "29. Governing law and jurisdiction",
      content: [
        "These Terms are governed by the laws of England and Wales.",
        "The courts of England and Wales shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms."
      ]
    },
    {
      title: "30. Contact",
      content: [
        "For questions about these Terms, please contact:",
        "WorkforceFlow AI Ltd",
        "Email: support@workforceflow.ai"
      ]
    }
  ];

  return (
    <div className="bg-white min-h-screen py-24 px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-10 text-slate-700 leading-7">
        <div className="overflow-hidden">
          
          {/* Main Content Area */}
          <div>
            
            {legalSections.map((section, idx) => {
              // Handle top-level headers (Company Name, Title)
              if (section.type === "header") {
                return (
                  <h1 key={idx} className="text-4xl font-bold text-slate-900 mb-3">
                    {section.content}
                  </h1>
                );
              }
              if (section.type === "subheader") {
                return (
                  <p key={idx} className="text-center text-slate-500 mb-10 border-b pb-8">
                    {section.content}
                  </p>
                );
              }
              if (section.type === "text") {
                return <p key={idx} className="mb-4">{section.content}</p>;
              }

              // Handle Numbered Sections
              return (
                <section key={idx} className="mb-8">
                  <h2 className="text-xl font-bold text-slate-900 mb-3">
                    {section.title}
                  </h2>
                  
                  {Array.isArray(section.content) ? (
  // If it's an array, map through the paragraphs
  section.content.map((p, pIdx) => (
    <p key={pIdx} className="mb-3">{p}</p>
  ))
) : (
  // If it's a string (for your top headers/text), render it directly
  <p className="mb-3">{section.content}</p>
)}

                  {section.bullets && (
                    <ul className="list-none space-y-2 my-4">
                      {section.bullets.map((bullet, bIdx) => (
                        <li key={bIdx} className="flex items-start pl-4">
                          <span className="mr-3 text-slate-400">•</span>
                          <span>{bullet}</span>
                        </li>
                      ))}
                    </ul>
                  )}

                  {section.footer && <p className="mt-3">{section.footer}</p>}
                </section>
              );
            })}
          </div>
        </div>

        
      </div>
    </div>
  );
};

export default TermsAndConditions;
